name: Build and publish a docker image

on:
  push:
    tags: [ 'v*' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      run: |
        docker login ghcr.io --username hellodhlyn --password ${{ secrets.GH_ACCESS_TOKEN }}

        docker build -t ghcr.io/hellodhlyn/s3-serve:latest .
        docker tag ghcr.io/hellodhlyn/s3-serve:latest ghcr.io/hellodhlyn/s3-serve:${GITHUB_REF##*/}

        docker push ghcr.io/hellodhlyn/s3-serve:latest
        docker push ghcr.io/hellodhlyn/s3-serve:${GITHUB_REF##*/}
